import {
  HelpCircle,
  Lightbulb,
  Bug,
  Code,
  MessageSquare,
  Settings,
} from 'lucide-react'
import type { ForumCategory } from './types'

export const forumCategories: ForumCategory[] = [
  {
    id: 'qa',
    name: 'Questions & Answers',
    description: 'Get help with integration issues and technical questions',
    icon: HelpCircle,
    color: 'text-blue-600 bg-blue-100',
    postCount: 1247,
    lastActivity: '2 minutes ago',
    moderators: ['SabPaisa Team', 'Community Moderators'],
  },
  {
    id: 'feature-requests',
    name: 'Feature Requests',
    description: 'Suggest new features and improvements',
    icon: Lightbulb,
    color: 'text-yellow-600 bg-yellow-100',
    postCount: 89,
    lastActivity: '1 hour ago',
    moderators: ['Product Team'],
  },
  {
    id: 'bug-reports',
    name: 'Bug Reports',
    description: 'Report issues and bugs you encounter',
    icon: Bug,
    color: 'text-red-600 bg-red-100',
    postCount: 156,
    lastActivity: '30 minutes ago',
    moderators: ['Engineering Team'],
  },
  {
    id: 'code-examples',
    name: 'Code Examples',
    description: 'Share and discuss integration code examples',
    icon: Code,
    color: 'text-green-600 bg-green-100',
    postCount: 234,
    lastActivity: '3 hours ago',
    moderators: ['Developer Advocates'],
  },
  {
    id: 'general',
    name: 'General Discussion',
    description: 'General discussions about SabPaisa and payments',
    icon: MessageSquare,
    color: 'text-purple-600 bg-purple-100',
    postCount: 567,
    lastActivity: '15 minutes ago',
    moderators: ['Community Team'],
  },
  {
    id: 'announcements',
    name: 'Announcements',
    description: 'Official announcements and updates',
    icon: Settings,
    color: 'text-indigo-600 bg-indigo-100',
    postCount: 23,
    lastActivity: '2 days ago',
    moderators: ['SabPaisa Team'],
  },
]
