import Link from 'next/link'

import { type IntegrationKitDoc } from '@/components/docs/integration-kit-docs'
import { IntegrationDocExplorer } from '@/components/docs/integration-doc-explorer'
import { apiReferenceKits } from '@/components/docs/api-reference-kits'
import { Button } from '@/components/ui/button'

const sandboxEndpoint = 'https://sandbox.api.sabpaisa.in/v1/payments'
const productionEndpoint = 'https://api.sabpaisa.in/v1/payments'
const defaultIntegrationVideoLink = 'https://www.youtube.com/watch?v=TO_BE_ADDED'
const encryptedRequest = 'U2FtcGxlRW5jcnlwdGVkUGF5bG9hZEVuY29kZWQ='
const encryptedResponse = 'QmFzZTY0RW5jcnlwdGVkUmVzcG9uc2VTYW1wbGU='

const toPrettyJson = (payload: unknown) => JSON.stringify(payload, null, 2)

const defaultEndpoints = {
  sandbox: sandboxEndpoint,
  production: productionEndpoint
} as const

const defaultRequestParameters: IntegrationKitDoc['requestParameters'] = [
  {
    name: 'merchantId',
    type: 'string',
    required: true,
    description: 'SabPaisa merchant code issued to your organisation.'
  },
  {
    name: 'orderId',
    type: 'string',
    required: true,
    description: 'Unique identifier generated by your system to track the transaction.'
  },
  {
    name: 'amount',
    type: 'number',
    required: true,
    description: 'Transaction amount expressed in paise for accuracy (₹1 = 100).'
  },
  {
    name: 'currency',
    type: 'string',
    required: true,
    description: 'ISO currency code. Use INR for Indian Rupee transactions.'
  },
  {
    name: 'callbackUrl',
    type: 'string',
    required: true,
    description: 'HTTPS URL to redirect the customer after checkout completion.'
  },
  {
    name: 'customer.name',
    type: 'string',
    required: true,
    description: 'Customer full name used for receipts and risk scoring.'
  },
  {
    name: 'customer.email',
    type: 'string',
    required: true,
    description: 'Customer contact email for transactional notifications.'
  },
  {
    name: 'customer.phone',
    type: 'string',
    required: true,
    description: 'Customer mobile number in E.164 format for OTP flows.'
  },
  {
    name: 'paymentMethod',
    type: 'string',
    required: false,
    description: 'Optional preference to pre-select CARD, UPI, NETBANKING, WALLET, or EMI.'
  },
  {
    name: 'metadata',
    type: 'object',
    required: false,
    description: 'Custom JSON object (4KB limit) to persist order context for reconciliation.'
  },
  {
    name: 'webhookUrl',
    type: 'string',
    required: false,
    description: 'Optional override for the webhook endpoint if different from portal configuration.'
  }
]

const defaultResponseParameters: IntegrationKitDoc['responseParameters'] = [
  {
    name: 'paymentId',
    type: 'string',
    description: 'SabPaisa payment reference used for status checks and captures.'
  },
  {
    name: 'status',
    type: 'string',
    description: 'Payment status. Expect PENDING immediately after creation.'
  },
  {
    name: 'redirectUrl',
    type: 'string',
    description: 'Hosted checkout URL to which the customer must be redirected.'
  },
  {
    name: 'expiresAt',
    type: 'string',
    description: 'ISO8601 timestamp indicating when the payment intent expires.'
  },
  {
    name: 'referenceId',
    type: 'string',
    description: 'Echo of your orderId or an auto-generated SabPaisa reference.'
  },
  {
    name: 'metadata',
    type: 'object',
    description: 'Metadata returned exactly as sent, with SabPaisa annotations where applicable.'
  },
  {
    name: 'signature',
    type: 'string',
    description: 'Hex encoded SHA256 signature of the response body.'
  }
]

const extendRequestParameters = (
  ...additional: Array<IntegrationKitDoc['requestParameters'][number]>
): IntegrationKitDoc['requestParameters'] => [...defaultRequestParameters, ...additional]

const extendResponseParameters = (
  ...additional: Array<IntegrationKitDoc['responseParameters'][number]>
): IntegrationKitDoc['responseParameters'] => [...defaultResponseParameters, ...additional]

const defaultRequestFormat: IntegrationKitDoc['requestFormat'] = {
  transport: 'Send a POST request over HTTPS (TLS 1.2+) to /v1/payments with a JSON body signed using your SabPaisa client secret.',
  headers: [
    'Content-Type: application/json',
    'X-SP-Client-Code: <your client code>',
    'X-SP-Request-Signature: Base64(HMAC-SHA256(payload, clientSecret))'
  ],
  bodyNotes: [
    'Amounts must be integers. Avoid floating point to prevent rounding differences.',
    'Include metadata for downstream reconciliation or analytics requirements.',
    'Keep callbackUrl on HTTPS with a publicly trusted certificate.'
  ]
}

const defaultResponseFormat: IntegrationKitDoc['responseFormat'] = {
  transport: 'SabPaisa returns JSON encoded responses and includes X-SP-Response-Signature for verification.',
  notes: [
    'Always validate the response signature before persisting payment state.',
    'Use webhooks to receive SUCCESS or FAILED updates; do not rely solely on redirect responses.',
    'Retry webhook acknowledgements with exponential backoff if you receive duplicate notifications.'
  ]
}

const createFrontendRequestFormat = (framework: string): IntegrationKitDoc['requestFormat'] => ({
  transport: `Collect card or mandate details inside your ${framework} application and relay them to a secure backend which issues the SabPaisa JSON request.`,
  headers: defaultRequestFormat.headers,
  bodyNotes: [
    'Serialize frontend form data into a backend-safe DTO before signing.',
    'Attach a deviceContext.metadata field capturing user agent for additional fraud signals.',
    'Ensure CSRF protection is in place when invoking your internal proxy endpoint.'
  ]
})

const createHybridRequestFormat = (framework: string): IntegrationKitDoc['requestFormat'] => ({
  transport: `${framework} apps should capture customer intent via platform-specific plugins and forward the payload to a backend API that communicates with SabPaisa.`,
  headers: defaultRequestFormat.headers,
  bodyNotes: [
    'Use secure storage (Keychain/Keystore) for temporary tokens before calling the backend.',
    'Capture deviceId and appVersion in metadata for downstream reporting.',
    'Prefer HTTPS-only communication and enable certificate pinning where supported.'
  ]
})

const createPluginRequestFormat = (platform: string, endpoint: string): IntegrationKitDoc['requestFormat'] => ({
  transport: `${platform} plugin calls should originate from the server-side hook provided by the module and POST JSON data to ${endpoint}.`,
  headers: [
    'Content-Type: application/json',
    'X-SP-Client-Code: <plugin client code>',
    'X-SP-Plugin-Id: <module identifier>',
    'X-SP-Request-Signature: Base64(HMAC-SHA256(payload, clientSecret))'
  ],
  bodyNotes: [
    'Generate order references using platform order keys to simplify reconciliation.',
    'Map billing and shipping data to the customer node before encryption.',
    'Respect plugin configuration flags (capture later, auto-refund, etc.) when building the payload.'
  ]
})

const createFrontendResponseFormat = (framework: string): IntegrationKitDoc['responseFormat'] => ({
  transport: `Responses arrive at your backend as JSON and should be relayed to the ${framework} client via secure APIs or websockets.`,
  notes: [
    'Propagate status updates to the UI along with redirectUrl for handoff.',
    'Persist the entire response body before notifying the frontend to prevent data loss.',
    'Leverage SabPaisa webhooks to keep the client UI in sync with asynchronous updates.'
  ]
})

const javaRequestParameters: IntegrationKitDoc['requestParameters'] = [
  { name: 'payerName', type: 'Alphabet', required: true, description: 'Full name of the payer (max 100 characters).' },
  { name: 'payerEmail', type: 'Alphabet', required: true, description: 'Email address of the payer (max 100 characters).' },
  { name: 'payerMobile', type: 'Numeric', required: true, description: 'Payer mobile number in international format (max 20 digits).' },
  { name: 'clientTxnId', type: 'AlphaNumeric', required: true, description: 'Unique transaction identifier generated by the merchant.' },
  { name: 'payerAddress', type: 'AlphaNumeric', required: false, description: 'Address details of the payer (optional, max 255 characters).' },
  { name: 'amount', type: 'Numeric', required: true, description: 'Amount to be collected, expressed in major currency units (max 10 digits).' },
  { name: 'clientCode', type: 'AlphaNumeric', required: true, description: 'SabPaisa client code assigned to the merchant (5 characters).' },
  { name: 'transUserName', type: 'AlphaNumeric', required: true, description: 'SabPaisa transaction username shared with the merchant.' },
  { name: 'transUserPassword', type: 'AlphaNumeric', required: true, description: 'SabPaisa transaction password shared with the merchant.' },
  { name: 'callbackUrl', type: 'AlphaNumeric', required: true, description: 'HTTPS callback URL that receives the encResponse payload.' },
  { name: 'amountType', type: 'Alphabet', required: false, description: 'Three-letter ISO currency code (defaults to INR).' },
  ...Array.from({ length: 20 }, (_, index) => ({
    name: `udf${index + 1}`,
    type: 'AlphaNumeric',
    required: false,
    description: `User defined field ${index + 1} (optional, max 255 characters).`
  })),
  { name: 'channelId', type: 'Alphabet', required: true, description: "Channel identifier: use 'W' for web, 'M' for mobile, 'npm' for Node.js package." },
  { name: 'programId', type: 'AlphaNumeric', required: false, description: 'Master client code when transacting under a program (optional).' },
  { name: 'mcc', type: 'Numeric', required: true, description: 'Merchant category code provided by SabPaisa.' },
  { name: 'transDate', type: 'Datetime', required: true, description: 'Transaction timestamp in the format yyyy-MM-dd HH:mm:ss.' }
]

const javaResponseParameters: IntegrationKitDoc['responseParameters'] = [
  { name: 'payerName', type: 'Alphabet', description: 'Name of the payer returned for reconciliation.' },
  { name: 'payerEmail', type: 'AlphaNumeric', description: 'Email address supplied by the payer.' },
  { name: 'payerMobile', type: 'Numeric', description: 'Payer mobile number forwarded in the response.' },
  { name: 'clientTxnId', type: 'AlphaNumeric', description: 'Merchant transaction identifier used in the request.' },
  { name: 'payerAddress', type: 'AlphaNumeric', description: 'Address information returned when provided.' },
  { name: 'amount', type: 'Numeric', description: 'Transaction amount captured in major currency units.' },
  { name: 'clientCode', type: 'Alphabet', description: 'SabPaisa client code associated with the transaction.' },
  { name: 'paidAmount', type: 'Numeric', description: 'Total amount collected from the payer (can differ due to surcharges/discounts).' },
  { name: 'paymentMode', type: 'Alphabet', description: 'Payment channel used (CARD, UPI, NETBANKING, WALLET, etc.).' },
  { name: 'bankName', type: 'Alphabet', description: 'Issuing bank name as supplied by the gateway/bank.' },
  { name: 'amountType', type: 'Alphabet', description: 'Currency code for the transaction.' },
  ...Array.from({ length: 20 }, (_, index) => ({
    name: `udf${index + 1}`,
    type: 'AlphaNumeric',
    description: `Echo of user defined field ${index + 1}.`
  })),
  { name: 'status', type: 'string', description: 'High-level transaction status (SUCCESS, FAILED, ABORTED, INITIATED, etc.).' },
  { name: 'statusCode', type: 'Numeric', description: 'SabPaisa status code corresponding to the transaction state.' },
  { name: 'challanNumber', type: 'AlphaNumeric', description: 'Generated challan number for offline payments (if applicable).' },
  { name: 'sabpaisaTxnId', type: 'Alphabet', description: 'Unique SabPaisa transaction identifier.' },
  { name: 'sabpaisaMessage', type: 'AlphaNumeric', description: 'Descriptive message returned by SabPaisa for the transaction.' },
  { name: 'bankMessage', type: 'AlphaNumeric', description: 'Message returned by the issuing bank or payment partner.' },
  { name: 'bankErrorCode', type: 'AlphaNumeric', description: 'Error code supplied by the bank when a transaction fails.' },
  { name: 'sabpaisaErrorCode', type: 'AlphaNumeric', description: 'Error code supplied by SabPaisa when available.' },
  { name: 'bankTxnId', type: 'AlphaNumeric', description: 'Transaction identifier returned by the bank/payment channel.' },
  { name: 'programId', type: 'AlphaNumeric', description: 'Program or master client code returned when applicable.' },
  { name: 'mcc', type: 'Numeric', description: 'Merchant category code returned in the response.' },
  { name: 'transDate', type: 'Datetime', description: 'Processing timestamp returned by SabPaisa.' },
  { name: 'rrn', type: 'string', description: 'Reference retrieval number when provided by the bank/issuer.' }
]

const javaRequestFormat: IntegrationKitDoc['requestFormat'] = {
  transport: 'Submit an HTTPS POST form to the SabPaisa init endpoint with two form fields: encData and clientCode.',
  headers: ['Content-Type: application/x-www-form-urlencoded'],
  bodyNotes: [
    'Concatenate all request parameters as key=value pairs separated by & before encryption.',
    'Encrypt the concatenated payload with AES256 + HMAC-SHA384 using the provided authKey/authIV to produce encData.',
    'Post encData and clientCode to the environment-specific URL once the mandatory parameters are populated.',
    'Ensure the clientTxnId is unique per transaction; duplicate values are rejected.'
  ]
}

const javaResponseFormat: IntegrationKitDoc['responseFormat'] = {
  transport: 'SabPaisa posts an encResponse payload to the callback URL. Decrypt using AES256 + HMAC-SHA384 to retrieve the key=value pairs.',
  notes: [
    'Always validate the decrypted payload before marking the transaction complete.',
    'Map statusCode values as follows: 0000=Success, 0300=Failed, 0100=Initiated, 0200=Aborted, 0400=Challan generated, 0999=Unknown, 404=Transaction not found.',
    'Persist sabpaisaTxnId, bankTxnId, and rrn for settlement and dispute workflows.'
  ]
}

const javaSampleEncryptedRequest = 'encData: A8ECE8F6AF57BD264B4F51369DE2A95F37B81B4A3AF41B1C8825ACB3B4B04FA7A4194A933365875ADB6FA68529A5A58F742E502C13BB8022C8711048A0DE8D52B62EB27AA437CD273CF9747BBE5F3E5B6E2DB6C96301D2DCDA39769758772BB0027FAA3CB89E67074C1193EFEC1E1E155D603CCDDD6BB2BC4C2CDB78212D745AD583CC7F7694149C00BF8AC3D3EFAE8D55788B30F6C1964211C97304309FAF65B9F53839AE7D95EAA4D6CB25696129AF8673232599FA1B3758E4C88EF08007EFB8BC0EF610A122F1794B637E2BCBB9E2EA31102C85427EA113E91104084503FA420886006778E2694350F023F33ED15ADE036442706F8416579E12E92F8DCD7790C18914A3089B7CDD1F549D2215EE9056FFDDB5D246A856D2325380AAEEED0ACBB2BD8AF32997921E19D9C23FBB3C9BC3FA84F785304900'
const javaSampleDecryptedRequest = 'payerName=vimalkumar&payerEmail=xyz@gmail.com&payerMobile=987456321&clientTxnId=SD2MHLRTP2UKZ2B7AYGY&amount=5&clientCode=DJ020&transUserName=DJL754@sp&transUserPassword=4q3qhgmJNM4m&callbackUrl=http://localhost:8080/response&channelId=W'

const javaSampleEncryptedResponse = 'encResponse: 6675E6836AC42838C9531381EEC1846A5DA18A77C57FC1E623AB7F7AA8A7CDA45DF696B15B11D259C5A4A40C6022F4CF8A5EB2FCB2ECDB1946A696470E01B305B83554CE6B34597B501712877C35E1B9FE75AD29DE7BF674AED29132655E4432199DEC8D02652D48EF32C81321F049E791E8C28076EB399185BE7BD2CE2E413B410495D53E3C8BF9B506D0D6CA9EE867DF8F1B6CBD5FBB76315CDE59CFBA5C7AE6EDC08A280AFB0FE663D37628B9BD1A5B2D9D2C8F34CEF6739E7C4A1A477046C5B1EFE1DE797C599A9F378C41D32B735F73CC1CE928EAB21E22915B477B8BF1F962866CBEA8819223BEE7F96AF3162AD33301D5FF0697C49112E09DA70CDE489CC3CBA8D8E745DE76E85E512ECE7CF199FE88D8DE5494E42A450E3A5D8B390BEEED35A82722491BAF441E5BF992A736A083ADA5478D7714F7E16FC858033194F22DCD99CC085062C754176022BE7953C452BF6B1E0065919B65AC388BD4ED2500A5CB7DEC828300827FE66F6EAA9C811D472E0EB09BED9D376A67C30E75AAFF7FBCBC36605490C5179DC315C80B8018F5624C504DBB3CDEA03785E72934642EE05549A5F392C8064BF8C38393472F45B3B24C9F2941DCA8BFA3D19AB9107C7054943EA6EF5AF9C6E6C1F0DB9920AE7367E2376B750BC47B6A3BB110DC0CA720063E3BD4CD55B13C63070253B518D65F18848EAE15ED70ABC64A23C140E50E6C6237A3059B2FAD0F0AC9E11F048BB3DACB44F3BA238B71300C835D1EAD7DCC4A02E9EE3FF4E651082CF6CF9C76CED6C90895C05C650D0F01C240B1959D49F305AB706C4F1FC9AE97F611C050FBCF465870C44755FF03D33DFEA84EE1AFE31DB14D8F680598EBBC2C9E742F0CEABDD008254FF9941FB0A32D9B4A6BD6B88254B91F876B260710A08B1EDF81B4B478000A6C9AF9887A224E5388B55BF46AAB844D224A4777377F36C8982DCB1E1014A3E07EBADEB8F70ED9B45A3515F759075B19102D3CF59D88D7844CB8B520DD60AD7CA5C633918FC5'
const javaSampleDecryptedResponse = 'payerName=vimalkumar&payerEmail=xyz@gmail.com&payerMobile=987456321&clientTxnId=SD2MHLRTP2UKZ2B7AYGY&payerAddress=NA&amount=5.0&clientCode=DJ020&paidAmount=null&paymentMode=&bankName=&amountType=INR&status=ABORTED&statusCode=0200&challanNumber=null&sabpaisaTxnId=&sabpaisaMessage=Payer cancelled the transaction before completion&bankMessage=&bankErrorCode=&sabpaisaErrorCode=CH0005&bankTxnId=&transDate=Mon Jun 30 13:09:00 IST 2025&udf1=NA&udf2=NA&udf3=NA&udf4=NA&udf5=NA&udf6=NA&udf7=NA&udf8=NA&udf9=null&udf10=null&udf11=null&udf12=null&udf13=null&udf14=null&udf15=null&udf16=null&udf17=null&udf18=null&udf19=null&udf20=null&rrn='

type Metadata = Record<string, string>

type CreatePayloadOptions = {
  initiatedBy: string
  metadata?: Metadata
  extras?: Record<string, unknown>
}

const createRequestPayload = ({
  initiatedBy,
  metadata = {},
  extras = {}
}: CreatePayloadOptions) =>
  toPrettyJson({
    merchantId: 'MERCHANT_SERVER',
    orderId: 'ORD-90210',
    amount: 125000,
    currency: 'INR',
    callbackUrl: 'https://merchant.example.com/payments/return',
    customer: {
      name: 'Aarav Malhotra',
      email: 'aarav@example.com',
      phone: '+919876543210'
    },
    paymentMethod: 'CARD',
    metadata: {
      initiatedBy,
      ...metadata
    },
    ...extras
  })

const createResponsePayload = ({
  initiatedBy,
  metadata = {},
  extras = {}
}: CreatePayloadOptions) =>
  toPrettyJson({
    paymentId: 'PAY-178234',
    status: 'PENDING',
    redirectUrl: 'https://checkout.sabpaisa.in/PAY-178234',
    expiresAt: '2025-02-01T12:30:00Z',
    referenceId: 'ORD-90210',
    metadata: {
      initiatedBy,
      ...metadata
    },
    signature: '7ad4f8d8a26d0e7b4fda716c3a0512fa',
    ...extras
  })

type BuildKitOptions = {
  purpose: string
  useCases: string[]
  prerequisites: string[]
  setup: string[]
  sampleCodeLink: string
  requestFormat?: IntegrationKitDoc['requestFormat']
  responseFormat?: IntegrationKitDoc['responseFormat']
  requestParameters?: IntegrationKitDoc['requestParameters']
  responseParameters?: IntegrationKitDoc['responseParameters']
  metadataTag: string
  requestMetadata?: Metadata
  responseMetadata?: Metadata
  requestExtras?: Record<string, unknown>
  responseExtras?: Record<string, unknown>
  endpoints?: IntegrationKitDoc['endpoints']
  integrationVideoLink?: string
  sampleEncryptedRequestOverride?: string
  sampleDecryptedRequestOverride?: string
  sampleEncryptedResponseOverride?: string
  sampleDecryptedResponseOverride?: string
}

const buildKit = (id: string, name: string, options: BuildKitOptions): IntegrationKitDoc => ({
  id,
  name,
  overview: {
    purpose: options.purpose,
    useCases: options.useCases,
    prerequisites: options.prerequisites,
    setup: options.setup
  },
  sampleCodeLink: options.sampleCodeLink,
  endpoints: options.endpoints ?? defaultEndpoints,
  requestFormat: options.requestFormat ?? defaultRequestFormat,
  requestParameters: options.requestParameters ?? defaultRequestParameters,
  sampleEncryptedRequest: options.sampleEncryptedRequestOverride ?? encryptedRequest,
  sampleDecryptedRequest:
    options.sampleDecryptedRequestOverride ??
    createRequestPayload({
      initiatedBy: options.metadataTag,
      metadata: options.requestMetadata,
      extras: options.requestExtras
    }),
  responseFormat: options.responseFormat ?? defaultResponseFormat,
  responseParameters: options.responseParameters ?? defaultResponseParameters,
  sampleEncryptedResponse: options.sampleEncryptedResponseOverride ?? encryptedResponse,
  sampleDecryptedResponse:
    options.sampleDecryptedResponseOverride ??
    createResponsePayload({
      initiatedBy: options.metadataTag,
      metadata: options.responseMetadata,
      extras: options.responseExtras
    }),
  integrationVideoLink: options.integrationVideoLink ?? defaultIntegrationVideoLink
})

const serverIntegrationKits: IntegrationKitDoc[] = [
  buildKit('java', 'Java', {
    purpose: 'Implement the SabPaisa payment gateway from Java or Spring services using encrypted payload hand-offs and seamless hosted checkout.',
    useCases: [
      'Java/Spring commerce portals that redirect payers to SabPaisa for secure checkout',
      'Enterprise or government applications needing encrypted payment initiation over HTTPS',
      'Legacy JEE systems migrating from other gateways while keeping server-side orchestration'
    ],
    prerequisites: [
      'Merchant runtime (Java/Spring) prepared with SabPaisa documentation, SDK, or plugin along with UAT credentials shared by SabPaisa',
      'Seamless flag enabled by the SabPaisa backend team for the merchant account',
      'Client code, transaction username/password, authKey, authIV, and callback URL stored securely in the application configuration'
    ],
    setup: [
      'Collect mandatory payer inputs (name, email, mobile, amount) on the merchant form and generate a unique clientTxnId for every attempt',
      'Build the request query string (key=value pairs joined with &) and encrypt it using AES256 + HMAC-SHA384 to produce encData',
      'POST encData and clientCode to the environment-specific init URL (sandbox or production) over HTTPS',
      'Let the payer authenticate on the SabPaisa payment page (OTP, card details, UPI PIN, etc.) and complete the payment',
      'Receive encResponse on the callbackUrl, decrypt using authKey/authIV, and update local order state using status/statusCode plus sabpaisaTxnId'
    ],
    sampleCodeLink: 'https://github.com/sabpaisa/integration-java-starter',
    endpoints: {
      sandbox: 'https://stage-securepay.sabpaisa.in/SabPaisa/sabPaisaInit?v=1',
      production: 'https://securepay.sabpaisa.in/SabPaisa/sabPaisaInit?v=1'
    },
    metadataTag: 'JAVA_BACKEND',
    requestMetadata: { framework: 'SpringBoot' },
    responseMetadata: { framework: 'SpringBoot' },
    requestFormat: javaRequestFormat,
    requestParameters: javaRequestParameters,
    sampleEncryptedRequestOverride: javaSampleEncryptedRequest,
    sampleDecryptedRequestOverride: javaSampleDecryptedRequest,
    responseFormat: javaResponseFormat,
    responseParameters: javaResponseParameters,
    sampleEncryptedResponseOverride: javaSampleEncryptedResponse,
    sampleDecryptedResponseOverride: javaSampleDecryptedResponse,
    integrationVideoLink: 'https://youtu.be/d-MPz7mGSqY?si=HfAr0kA2psRuO9Lt'
  }),
  buildKit('php', 'PHP', {
    purpose: 'Process SabPaisa transactions from PHP runtimes with cURL-based signing helpers and webhook middleware.',
    useCases: [
      'CodeIgniter or Symfony e-commerce storefronts',
      'Laravel-based subscription billing platforms',
      'Command-line PHP scripts reconciling payout batches'
    ],
    prerequisites: [
      'PHP 8.1+ with ext-json and ext-curl enabled',
      'Composer for dependency management',
      'Secure configuration storage (dotenv, Vault, or parameter store)'
    ],
    setup: [
      'Install sabpaisa/sdk via Composer',
      'Publish the config file and set SP_CLIENT_CODE and SP_CLIENT_SECRET',
      'Add middleware to verify X-SP-Response-Signature on webhooks',
      'Trigger sandbox payment creation from your staging environment'
    ],
    sampleCodeLink: 'https://github.com/sabpaisa/integration-php-starter',
    metadataTag: 'PHP_GATEWAY',
    requestMetadata: { framework: 'Laravel' },
    responseMetadata: { framework: 'Laravel' },
    integrationVideoLink: 'https://youtu.be/EAPQ83F7lKY?si=K_8nAELl6QGyduhS'
  }),
  buildKit('laravel', 'Laravel', {
    purpose: 'Use Laravel\'s queues and HTTP client to manage payment intents, retries, and webhook handling in a first-class manner.',
    useCases: [
      'Membership portals orchestrating recurring payments',
      'Multi-tenant SaaS dashboards requiring scoped credentials per tenant',
      'Donation platforms automating payment reminders'
    ],
    prerequisites: [
      'Laravel 10.x project with queue worker configured',
      'Redis, SQS, or RabbitMQ for background jobs',
      'Configured application key rotation policy for SabPaisa secrets'
    ],
    setup: [
      'Install sabpaisa/laravel-sdk Composer package',
      'Publish configuration via php artisan vendor:publish',
      'Implement webhook controller with signature verification middleware',
      'Write feature tests covering sandbox transaction lifecycle'
    ],
    sampleCodeLink: 'https://github.com/sabpaisa/integration-laravel-starter',
    metadataTag: 'LARAVEL_BACKEND',
    requestMetadata: { framework: 'Laravel', queue: 'redis' },
    responseMetadata: { framework: 'Laravel', queue: 'redis' },
    integrationVideoLink: 'https://youtu.be/b0DmQU-zYiI?si=teUyf5gIICFJrhPg'
  }),
  buildKit('nodejs', 'Node.js', {
    purpose: 'Integrate SabPaisa with Node.js or TypeScript services using async/await friendly clients and native crypto modules.',
    useCases: [
      'Next.js API routes executing server-side payment creation',
      'Express or Fastify services powering marketplaces',
      'Serverless payment processors on AWS Lambda or Azure Functions'
    ],
    prerequisites: [
      'Node.js 18+ runtime (ESM compatible)',
      'dotenv or secrets manager for credential storage',
      'Fetch or Axios configured with TLS 1.2 support'
    ],
    setup: [
      'npm install @sabpaisa/node-sdk',
      'Instantiate the client with client code and secret',
      'Add middleware to validate webhook signatures using crypto.subtle',
      'Run sandbox integration tests covering success and failure paths'
    ],
    sampleCodeLink: 'https://github.com/sabpaisa/integration-node-starter',
    metadataTag: 'NODE_BACKEND',
    requestMetadata: { framework: 'Express' },
    responseMetadata: { framework: 'Express' },
    integrationVideoLink: 'https://youtu.be/QuMeziNN0dM?si=1FtmB2w1NmbJ_1gw'
  }),
  buildKit('python', 'Python', {
    purpose: 'Leverage Python frameworks (Django, Flask, FastAPI) to orchestrate payments with typed clients and webhook verifiers.',
    useCases: [
      'Django admin panels processing manual invoices',
      'FastAPI microservices providing RESTful checkout endpoints',
      'Automation scripts reconciling settlements nightly'
    ],
    prerequisites: [
      'Python 3.10+ environment',
      'httpx or requests library with TLS 1.2 support',
      'Virtual environment or container for dependency isolation'
    ],
    setup: [
      'pip install sabpaisa-sdk',
      'Configure environment variables for SP_CLIENT_CODE and SP_CLIENT_SECRET',
      'Expose webhook endpoint and validate signatures using provided helper',
      'Simulate sandbox transactions and confirm webhook acknowledgement'
    ],
    sampleCodeLink: 'https://github.com/sabpaisa/integration-python-starter',
    metadataTag: 'PYTHON_BACKEND',
    requestMetadata: { framework: 'FastAPI' },
    responseMetadata: { framework: 'FastAPI' }
  }),
  buildKit('dotnet', '.NET', {
    purpose: 'Integrate SabPaisa into ASP.NET Core or Azure Functions using HttpClient factories and dependency injection.',
    useCases: [
      'ASP.NET Core Web APIs driving enterprise checkout',
      'Azure Durable Functions orchestrating multi-step payment flows',
      'Windows services automating bulk disbursement operations'
    ],
    prerequisites: [
      '.NET 8 SDK with nullable reference types enabled',
      'Configured HttpClientFactory with retry policies',
      'Azure Key Vault or user secrets storing SabPaisa credentials'
    ],
    setup: [
      'dotnet add package SabPaisa.SDK',
      'Register SabPaisaClient and signature validator in DI container',
      'Add webhook endpoint with HMAC validation middleware',
      'Deploy to staging slot and validate sandbox payment + webhook'
    ],
    sampleCodeLink: 'https://github.com/sabpaisa/integration-dotnet-starter',
    metadataTag: 'DOTNET_BACKEND',
    requestMetadata: { framework: 'AspNetCore' },
    responseMetadata: { framework: 'AspNetCore' },
    integrationVideoLink: 'https://youtu.be/HqBpn5PrnMo?si=EFwJCcfON4PAJs94'
  })
]

const webIntegrationKits: IntegrationKitDoc[] = [
  buildKit('reactjs', 'ReactJS', {
    purpose: 'Create rich checkout experiences in React and offload sensitive payment communication to a trusted backend service.',
    useCases: [
      'Single-page applications embedding SabPaisa checkout modals',
      'Next.js storefronts orchestrating server actions with client hints',
      'Partner dashboards enabling on-demand invoice settlement'
    ],
    prerequisites: [
      'React 18+ with hooks enabled',
      'Backend proxy endpoint to sign and forward payment requests',
      'CSRF tokens or same-site cookies to secure client ➜ server calls'
    ],
    setup: [
      'Install @sabpaisa/react-sdk for UI helpers and hooks',
      'Configure environment variables for backend proxy endpoints',
      'Leverage React Query/SWR to fetch sandbox payment configuration',
      'Implement success and error toasts reflecting webhook updates'
    ],
    sampleCodeLink: 'https://github.com/sabpaisa/integration-react-starter',
    metadataTag: 'REACT_WEB',
    requestMetadata: { framework: 'React', build: 'Vite' },
    responseMetadata: { framework: 'React', build: 'Vite' },
    requestFormat: createFrontendRequestFormat('React'),
    responseFormat: createFrontendResponseFormat('React'),
    requestParameters: extendRequestParameters(
      {
        name: 'deviceContext.ip',
        type: 'string',
        required: false,
        description: 'Client IP captured from the browser for risk analysis.'
      },
      {
        name: 'sessionId',
        type: 'string',
        required: false,
        description: 'Frontend session identifier to reconcile UI notifications.'
      }
    ),
    responseParameters: extendResponseParameters({
      name: 'uiHints',
      type: 'object',
      description: 'Optional recommendations to drive the React UI (e.g., showOtpScreen).'
    }),
    requestExtras: {
      channel: 'WEB',
      sessionId: 'SESSION-REACT-001',
      deviceContext: {
        ip: '203.0.113.42',
        userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 14_2) AppleWebKit/605.1.15'
      }
    },
    responseExtras: {
      uiHints: {
        nextAction: 'REDIRECT',
        message: 'Redirect customer to hosted checkout'
      }
    },
    integrationVideoLink: 'https://youtu.be/TxMlfI8NDig?si=J3xW28MROCxfqULA'
  }),
  buildKit('angularjs', 'AngularJS', {
    purpose: 'Use Angular services and interceptors to manage SabPaisa payment flows with strict typing and RxJS observables.',
    useCases: [
      'Enterprise admin portals with granular role-based access',
      'Component libraries exposing reusable payment widgets',
      'Multi-step wizards collecting customer mandates'
    ],
    prerequisites: [
      'Angular 16+ project with HttpClientModule',
      'Backend BFF (Backend-for-Frontend) service for signing requests',
      'Configured environment.ts for sandbox vs production settings'
    ],
    setup: [
      'Install @sabpaisa/angular-sdk and register SabPaisaModule',
      'Generate PaymentService to orchestrate calls to your backend proxy',
      'Implement route guards to handle redirect return flows',
      'Write Cypress or Playwright specs covering sandbox checkout journey'
    ],
    sampleCodeLink: 'https://github.com/sabpaisa/integration-angular-starter',
    metadataTag: 'ANGULAR_WEB',
    requestMetadata: { framework: 'Angular', version: '16.2' },
    responseMetadata: { framework: 'Angular', version: '16.2' },
    requestFormat: createFrontendRequestFormat('Angular'),
    responseFormat: createFrontendResponseFormat('Angular'),
    requestParameters: extendRequestParameters(
      {
        name: 'deviceContext.timezone',
        type: 'string',
        required: false,
        description: 'Browser-reported timezone to improve risk scoring.'
      }
    ),
    responseParameters: extendResponseParameters({
      name: 'uiHints',
      type: 'object',
      description: 'Signals to help Angular components render the correct state.'
    }),
    requestExtras: {
      channel: 'WEB',
      sessionId: 'SESSION-ANGULAR-001',
      deviceContext: {
        ip: '198.51.100.24',
        userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
        timezone: 'Asia/Kolkata'
      }
    },
    responseExtras: {
      uiHints: {
        nextAction: 'SHOW_STATUS',
        message: 'Display confirmation banner'
      }
    },
    integrationVideoLink: 'https://youtu.be/Qzy2r2aLIDk?si=D3jzgLPpA9Z5I0Ca'
  }),
  buildKit('vuejs', 'Vue.js', {
    purpose: 'Integrate SabPaisa with Vue 3 composition API for lightweight, reactive web checkout flows.',
    useCases: [
      'Vue storefronts requiring quick embed of SabPaisa payment button',
      'Nuxt server-side rendered experiences with hybrid rendering',
      'Operational dashboards enabling manual payment retriggers'
    ],
    prerequisites: [
      'Vue 3 with composition API',
      'Axios or Fetch wrapper pointing to backend proxy endpoints',
      'Pinia/Vuex store to persist payment session state'
    ],
    setup: [
      'Install @sabpaisa/vue-sdk plugin',
      'Create composables for payment intent creation and status polling',
      'Handle redirect callback inside router.afterEach to resume state',
      'Configure sandbox credentials via environment variables'
    ],
    sampleCodeLink: 'https://github.com/sabpaisa/integration-vue-starter',
    metadataTag: 'VUE_WEB',
    requestMetadata: { framework: 'Vue', mode: 'SSR' },
    responseMetadata: { framework: 'Vue', mode: 'SSR' },
    requestFormat: createFrontendRequestFormat('Vue'),
    responseFormat: createFrontendResponseFormat('Vue'),
    requestParameters: extendRequestParameters(
      {
        name: 'deviceContext.locale',
        type: 'string',
        required: false,
        description: 'Locale identifier to render localized checkout messaging.'
      }
    ),
    responseParameters: extendResponseParameters({
      name: 'uiHints',
      type: 'object',
      description: 'Helper hints to feed into Vue state (e.g., showMandateOverlay).'
    }),
    requestExtras: {
      channel: 'WEB',
      sessionId: 'SESSION-VUE-001',
      deviceContext: {
        ip: '192.0.2.19',
        userAgent: 'Mozilla/5.0 (X11; Linux x86_64)',
        locale: 'en-IN'
      }
    },
    responseExtras: {
      uiHints: {
        nextAction: 'DISPLAY_REDIRECT',
        message: 'Open SabPaisa hosted checkout in new tab'
      }
    },
    integrationVideoLink: 'https://youtu.be/6_PlHlCXUYs?si=orc1GpXC1LdvV8YL'
  })
]

const hybridIntegrationKits: IntegrationKitDoc[] = [
  buildKit('flutter', 'Flutter', {
    purpose: 'Ship cross-platform Flutter apps with SabPaisa integrated via platform channels and secure backend proxies.',
    useCases: [
      'Consumer fintech apps requiring native-like payment flows',
      'Agent collection applications with offline support and sync',
      'Mobile dashboards for subscription management'
    ],
    prerequisites: [
      'Flutter 3.19+ with Dart 3',
      'Secure storage plugin (flutter_secure_storage) for tokens',
      'Backend endpoint to sign and store SabPaisa intents'
    ],
    setup: [
      'Add sabpaisa_flutter package via pubspec.yaml',
      'Implement MethodChannel to call backend proxy for payment creation',
      'Handle deep links or universal links for redirect responses',
      'Test sandbox flows on both Android and iOS simulators'
    ],
    sampleCodeLink: 'https://github.com/sabpaisa/integration-flutter-starter',
    metadataTag: 'FLUTTER_HYBRID',
    requestMetadata: { framework: 'Flutter', platform: 'mobile' },
    responseMetadata: { framework: 'Flutter', platform: 'mobile' },
    requestFormat: createHybridRequestFormat('Flutter'),
    responseFormat: defaultResponseFormat,
    requestParameters: extendRequestParameters(
      {
        name: 'deviceContext.deviceId',
        type: 'string',
        required: false,
        description: 'Hashed device identifier used for fraud controls.'
      },
      {
        name: 'deviceContext.platform',
        type: 'string',
        required: false,
        description: 'Platform string (android, ios) reported by Flutter runtime.'
      }
    ),
    requestExtras: {
      channel: 'MOBILE',
      deviceContext: {
        deviceId: 'a1b2c3d4e5f6',
        platform: 'android',
        appVersion: '2.4.1'
      }
    },
    responseExtras: {
      platformHints: {
        preferDeepLink: true
      }
    },
    responseParameters: extendResponseParameters({
      name: 'platformHints',
      type: 'object',
      description: 'Mobile-specific hints to decide between webview or deep-link checkout flows.'
    }),
    integrationVideoLink: 'https://youtu.be/sRHGb6nd8Rg?si=-e8j8fXSbEHZfT7B'
  }),
  buildKit('react-native', 'React Native', {
    purpose: 'Reuse React Native components to trigger SabPaisa payments while delegating sensitive work to secure backend services.',
    useCases: [
      'Consumer subscription apps needing unified Android/iOS flow',
      'Marketplace couriers collecting COD settlements',
      'Mobile CRM apps enabling on-site payment acceptance'
    ],
    prerequisites: [
      'React Native 0.74+ environment',
      'Secure storage (AsyncStorage + native secure storage) for tokens',
      'Backend proxy accessible over HTTPS'
    ],
    setup: [
      'Install @sabpaisa/react-native-sdk',
      'Implement native module to open SabPaisa webview or deep link',
      'Use react-query to poll backend for payment status',
      'Validate sandbox flows on physical devices for OTP handling'
    ],
    sampleCodeLink: 'https://github.com/sabpaisa/integration-react-native-starter',
    metadataTag: 'RN_HYBRID',
    requestMetadata: { framework: 'ReactNative' },
    responseMetadata: { framework: 'ReactNative' },
    requestFormat: createHybridRequestFormat('React Native'),
    responseFormat: defaultResponseFormat,
    requestExtras: {
      channel: 'MOBILE',
      deviceContext: {
        deviceId: 'rn-device-id',
        platform: 'ios',
        appVersion: '1.10.0'
      }
    }
  }),
  buildKit('cordova', 'Cordova', {
    purpose: 'Support legacy hybrid applications built on Cordova while still meeting SabPaisa security guidelines.',
    useCases: [
      'Field collection apps maintained on Cordova',
      'Retail POS solutions running in kiosk mode',
      'Government service apps with minimal footprint'
    ],
    prerequisites: [
      'Cordova CLI 12+',
      'Whitelisted domains configuration for SabPaisa URLs',
      'Backend API exposed for secure payment creation'
    ],
    setup: [
      'Install cordova-plugin-sabpaisa',
      'Configure allow-navigation directives for sandbox and production domains',
      'Integrate plugin callbacks to trigger backend payment creation',
      'Exercise sandbox flows focusing on offline retry scenarios'
    ],
    sampleCodeLink: 'https://github.com/sabpaisa/integration-cordova-starter',
    metadataTag: 'CORDOVA_HYBRID',
    requestMetadata: { framework: 'Cordova' },
    responseMetadata: { framework: 'Cordova' },
    requestFormat: createHybridRequestFormat('Cordova'),
    responseFormat: defaultResponseFormat,
    integrationVideoLink: 'https://youtu.be/Q9Udpggc6uQ?si=gAokUOsKtsrDNhdW'
  }),
  buildKit('capacitor', 'Capacitor', {
    purpose: 'Use Capacitor runtime for modern hybrid apps that bridge web and native experiences with SabPaisa.',
    useCases: [
      'Capacitor apps needing push notifications for payment updates',
      'Embedded finance experiences inside partner apps',
      'Cross-platform internal tooling with hardware integrations'
    ],
    prerequisites: [
      'Capacitor 6+ with Android and iOS platforms added',
      'Secure storage plugin for secrets and tokens',
      'Backend integration for SabPaisa request forwarding'
    ],
    setup: [
      'npm install @sabpaisa/capacitor-plugin',
      'Register plugin with Capacitor config and sync platforms',
      'Handle deep links from SabPaisa checkout using App.addListener',
      'Validate sandbox transactions across both platforms'
    ],
    sampleCodeLink: 'https://github.com/sabpaisa/integration-capacitor-starter',
    metadataTag: 'CAPACITOR_HYBRID',
    requestMetadata: { framework: 'Capacitor' },
    responseMetadata: { framework: 'Capacitor' },
    requestFormat: createHybridRequestFormat('Capacitor'),
    responseFormat: defaultResponseFormat
  }),
  buildKit('ionic', 'Ionic', {
    purpose: 'Leverage Ionic components with SabPaisa backend integration for responsive hybrid payment flows.',
    useCases: [
      'Retail associate apps managing assisted payments',
      'Utility payment apps offering multi-channel checkout',
      'Healthcare collection solutions requiring offline-first capability'
    ],
    prerequisites: [
      'Ionic 7+ with Angular or React stack',
      'Secure token storage strategy',
      'Backend microservice for payment orchestration'
    ],
    setup: [
      'npm install @sabpaisa/ionic-sdk',
      'Integrate Ionic UI components with payment state machine',
      'Register deep link handlers for success/failure return URLs',
      'Perform sandbox smoke tests covering retries and cancellations'
    ],
    sampleCodeLink: 'https://github.com/sabpaisa/integration-ionic-starter',
    metadataTag: 'IONIC_HYBRID',
    requestMetadata: { framework: 'Ionic' },
    responseMetadata: { framework: 'Ionic' },
    requestFormat: createHybridRequestFormat('Ionic'),
    responseFormat: defaultResponseFormat
  })
]

const nativeIntegrationKits: IntegrationKitDoc[] = [
  buildKit('ios', 'iOS', {
    purpose: 'Integrate SabPaisa with native iOS apps using Swift concurrency, URLSession, and universal links.',
    useCases: [
      'iOS banking apps embedding native checkout flows',
      'Enterprise field apps capturing mandates on-site',
      'Retail in-app payments requiring Face ID/Touch ID authentication'
    ],
    prerequisites: [
      'iOS 15+ deployment target',
      'Keychain access group for secure credential storage',
      'Universal links configured for SabPaisa redirect handling'
    ],
    setup: [
      'Add SabPaisaSwiftSDK via Swift Package Manager',
      'Create PaymentService leveraging URLSession with certificate pinning',
      'Implement SceneDelegate handlers for SabPaisa deep links',
      'Test sandbox flows on physical devices for OTP entry'
    ],
    sampleCodeLink: 'https://github.com/sabpaisa/integration-ios-starter',
    metadataTag: 'IOS_NATIVE',
    requestMetadata: { framework: 'Swift', platform: 'iOS' },
    responseMetadata: { framework: 'Swift', platform: 'iOS' },
    requestFormat: createHybridRequestFormat('iOS native'),
    responseFormat: defaultResponseFormat,
    requestExtras: {
      channel: 'MOBILE',
      deviceContext: {
        deviceId: 'ios-device-uuid',
        platform: 'iOS',
        appVersion: '5.3.0'
      }
    }
  }),
  buildKit('android', 'Android', {
    purpose: 'Connect SabPaisa to Android apps using Kotlin coroutines, OkHttp, and Jetpack libraries.',
    useCases: [
      'UPI-ready Android commerce apps',
      'Agent applications collecting payments in the field',
      'Mobile apps requiring offline caching and later sync'
    ],
    prerequisites: [
      'Android Studio Giraffe or newer',
      'Min SDK 24 with Kotlin 1.9',
      'EncryptedSharedPreferences or Android Keystore for secrets'
    ],
    setup: [
      'Include SabPaisa Android SDK via Gradle (MavenCentral)',
      'Create Retrofit service pointing to backend proxy for payment creation',
      'Handle CustomTabsIntent for SabPaisa hosted checkout',
      'Instrument sandbox scenarios across varied network conditions'
    ],
    sampleCodeLink: 'https://github.com/sabpaisa/integration-android-starter',
    metadataTag: 'ANDROID_NATIVE',
    requestMetadata: { framework: 'Kotlin', platform: 'Android' },
    responseMetadata: { framework: 'Kotlin', platform: 'Android' },
    requestFormat: createHybridRequestFormat('Android native'),
    responseFormat: defaultResponseFormat,
    requestExtras: {
      channel: 'MOBILE',
      deviceContext: {
        deviceId: 'android-device-uuid',
        platform: 'Android',
        appVersion: '4.2.7'
      }
    }
  })
]

const ecommerceIntegrationKits: IntegrationKitDoc[] = [
  buildKit('woocommerce-plugin', 'WooCommerce Plugin', {
    purpose: 'Install the SabPaisa WooCommerce plugin to accept payments without writing custom checkout code.',
    useCases: [
      'D2C brands requiring quick go-live on WooCommerce',
      'Merchants adding UPI and mandate support to existing stores',
      'Teams delegating payment maintenance to SabPaisa managed plugin'
    ],
    prerequisites: [
      'WordPress 6.x with WooCommerce 8.x',
      'Server support for TLS 1.2, cURL, and JSON extensions',
      'SabPaisa plugin credentials and callback URL configuration'
    ],
    setup: [
      'Upload sabpaisa-woocommerce.zip via WordPress plugin manager',
      'Configure sandbox credentials inside WooCommerce payment settings',
      'Enable webhook endpoint created by the plugin',
      'Place sandbox orders to validate status transitions'
    ],
    sampleCodeLink: 'https://github.com/sabpaisa/plugin-woocommerce',
    metadataTag: 'WOOCOMMERCE_PLUGIN',
    requestMetadata: { platform: 'WooCommerce' },
    responseMetadata: { platform: 'WooCommerce' },
    requestFormat: createPluginRequestFormat('WooCommerce', 'https://sandbox.api.sabpaisa.in/v1/plugins/woocommerce/orders'),
    responseFormat: {
      transport: 'Plugin webhook handlers receive JSON payloads and update WooCommerce order notes.',
      notes: [
        'Ensure the plugin response signature is validated before marking orders paid.',
        'WooCommerce order status is set based on the SabPaisa status field.',
        'Refunds triggered in WooCommerce are relayed to SabPaisa via plugin hooks.'
      ]
    },
    requestParameters: extendRequestParameters(
      {
        name: 'pluginMetadata.storeUrl',
        type: 'string',
        required: true,
        description: 'Origin URL of the WooCommerce store submitting the request.'
      },
      {
        name: 'pluginMetadata.pluginVersion',
        type: 'string',
        required: true,
        description: 'Version of the installed SabPaisa plugin for support diagnostics.'
      }
    ),
    responseParameters: extendResponseParameters(
      {
        name: 'orderStatus',
        type: 'string',
        description: 'Mapped WooCommerce order status after processing the response.'
      }
    ),
    endpoints: {
      sandbox: 'https://sandbox.api.sabpaisa.in/v1/plugins/woocommerce/orders',
      production: 'https://api.sabpaisa.in/v1/plugins/woocommerce/orders'
    }
  }),
  buildKit('odoo', 'Odoo', {
    purpose: 'Integrate SabPaisa with Odoo ERP using the official payment acquirer module.',
    useCases: [
      'Odoo eCommerce storefronts needing SabPaisa checkout',
      'ERP-driven invoicing workflows with automated reconciliation',
      'Partner marketplaces managed through Odoo backend'
    ],
    prerequisites: [
      'Odoo 17 enterprise or community edition',
      'Payment acquirer module installed with developer mode access',
      'SabPaisa credentials stored in Odoo system parameters'
    ],
    setup: [
      'Install sabpaisa_odoo_payment module',
      'Activate SabPaisa acquirer in Odoo settings and add sandbox keys',
      'Configure webhook controllers to accept SabPaisa callbacks',
      'Process test invoices to verify payment and settlement entries'
    ],
    sampleCodeLink: 'https://github.com/sabpaisa/plugin-odoo',
    metadataTag: 'ODOO_PLUGIN',
    requestMetadata: { platform: 'Odoo' },
    responseMetadata: { platform: 'Odoo' },
    requestFormat: createPluginRequestFormat('Odoo', 'https://sandbox.api.sabpaisa.in/v1/plugins/odoo/orders'),
    responseFormat: {
      transport: 'Odoo controllers receive JSON payloads and update payment transaction records.',
      notes: [
        'Validate the signature before setting transaction_state to done.',
        'Leverage Odoo schedulers to poll SabPaisa for reconciliation if webhooks fail.',
        'Map SabPaisa paymentId to Odoo acquirer reference for audits.'
      ]
    },
    endpoints: {
      sandbox: 'https://sandbox.api.sabpaisa.in/v1/plugins/odoo/orders',
      production: 'https://api.sabpaisa.in/v1/plugins/odoo/orders'
    }
  }),
  buildKit('wix', 'Wix', {
    purpose: 'Use the Wix custom payments integration to connect SabPaisa with Wix stores.',
    useCases: [
      'Small businesses spinning up Wix storefronts with SabPaisa support',
      'Event management sites collecting ticket payments',
      'Educational institutions hosting quick donation campaigns'
    ],
    prerequisites: [
      'Wix site with Developer Mode enabled',
      'SabPaisa credentials configured in Wix Secrets Manager',
      'Backend endpoint (Velo HTTP functions) to proxy SabPaisa requests'
    ],
    setup: [
      'Install sabpaisa-wix integration module via Velo',
      'Expose backend function to create payment intents with SabPaisa',
      'Configure Wix checkout settings to call the backend proxy',
      'Validate sandbox orders and ensure redirects return to Wix order summary'
    ],
    sampleCodeLink: 'https://github.com/sabpaisa/plugin-wix',
    metadataTag: 'WIX_PLUGIN',
    requestMetadata: { platform: 'Wix' },
    responseMetadata: { platform: 'Wix' },
    requestFormat: createPluginRequestFormat('Wix', 'https://sandbox.api.sabpaisa.in/v1/plugins/wix/orders'),
    responseFormat: {
      transport: 'Wix backend functions consume JSON responses and update order status via APIs.',
      notes: [
        'Ensure Wix backend functions validate SabPaisa signatures.',
        'Propagate redirectUrl back to Wix checkout page for automatic redirection.',
        'Log orderId and paymentId pairs in Wix Collections for traceability.'
      ]
    },
    endpoints: {
      sandbox: 'https://sandbox.api.sabpaisa.in/v1/plugins/wix/orders',
      production: 'https://api.sabpaisa.in/v1/plugins/wix/orders'
    }
  }),
  buildKit('opencart', 'OpenCart', {
    purpose: 'Add SabPaisa payment gateway to OpenCart stores via the maintained extension.',
    useCases: [
      'Merchants running OpenCart 3.x shops',
      'Channel partners operating multiple OpenCart tenants',
      'Retailers migrating from manual settlement flows'
    ],
    prerequisites: [
      'OpenCart 3.x with access to admin dashboard',
      'SabPaisa extension installed (OCMOD or VQMOD)',
      'Configured return and webhook URLs reachable from SabPaisa'
    ],
    setup: [
      'Upload sabpaisa-opencart extension and refresh modifications',
      'Enter sandbox credentials in payment extensions configuration',
      'Enable order status mappings for success, pending, and failed states',
      'Run sandbox test orders including refund scenarios'
    ],
    sampleCodeLink: 'https://github.com/sabpaisa/plugin-opencart',
    metadataTag: 'OPENCART_PLUGIN',
    requestMetadata: { platform: 'OpenCart' },
    responseMetadata: { platform: 'OpenCart' },
    requestFormat: createPluginRequestFormat('OpenCart', 'https://sandbox.api.sabpaisa.in/v1/plugins/opencart/orders'),
    responseFormat: {
      transport: 'SabPaisa sends JSON payloads which the OpenCart extension processes to update order history.',
      notes: [
        'Ensure the extension validates signatures before updating order history.',
        'Use OpenCart cron job to reconcile orders that remain pending.',
        'Store paymentId in order history comments for downstream reference.'
      ]
    },
    endpoints: {
      sandbox: 'https://sandbox.api.sabpaisa.in/v1/plugins/opencart/orders',
      production: 'https://api.sabpaisa.in/v1/plugins/opencart/orders'
    }
  })
]

const integrationDocCategories = [
  {
    id: 'server-integration',
    title: 'Server Integration',
    kits: serverIntegrationKits
  },
  {
    id: 'web-integration',
    title: 'Web Integration',
    kits: webIntegrationKits
  },
  {
    id: 'hybrid-integration',
    title: 'Hybrid Integration',
    kits: hybridIntegrationKits
  },
  {
    id: 'native-integration',
    title: 'Native Integration',
    kits: nativeIntegrationKits
  },
  {
    id: 'ecommerce-plugin',
    title: 'E-commerce Plugin',
    kits: ecommerceIntegrationKits
  },
  {
    id: 'api-reference',
    title: 'API Reference',
    kits: apiReferenceKits
  }
] as const


export default function DocsPage() {
  return (
    <div className="mx-auto max-w-6xl space-y-12 px-6 py-12">
      <IntegrationDocExplorer categories={integrationDocCategories} />

      <div className="rounded-3xl border border-border/60 bg-muted/30 p-10 shadow-inner">
        <h2 className="text-2xl font-semibold">Need help?</h2>
        <p className="mt-2 max-w-2xl text-muted-foreground">
          Can't find what you're looking for? Drop into the community forum for peer support or raise a ticket with our integration specialists.
        </p>
        <div className="mt-6 flex flex-col gap-3 sm:flex-row">
          <Button asChild className="rounded-full">
            <Link href="/community">Visit community forum</Link>
          </Button>
          <Button asChild variant="outline" className="rounded-full">
            <Link href="/contact">Contact support</Link>
          </Button>
        </div>
      </div>
    </div>
  )
}
