import type { IntegrationKitDoc } from './integration-kit-docs'

const transactionEnquiryRequestParameters: IntegrationKitDoc['requestParameters'] = [
  { name: 'payerName', type: 'Alphabet', required: true, description: 'Name of the payer.' },
  { name: 'payerEmail', type: 'Alphabet', required: true, description: 'Email address of the payer.' },
  { name: 'payerMobile', type: 'Numeric', required: true, description: 'Mobile number of the payer.' },
  { name: 'clientTxnId', type: 'AlphaNumeric', required: true, description: 'Transaction ID generated by the client.' },
  { name: 'payerAddress', type: 'AlphaNumeric', required: false, description: 'Address of the payer.' },
  { name: 'amount', type: 'Numeric', required: true, description: 'Transaction amount.' },
  { name: 'clientCode', type: 'AlphaNumeric', required: true, description: 'Client code assigned by SabPaisa.' },
  { name: 'transUserName', type: 'AlphaNumeric', required: true, description: 'Username shared by SabPaisa.' },
  { name: 'transUserPassword', type: 'AlphaNumeric', required: true, description: 'Password shared by SabPaisa.' },
  { name: 'callbackUrl', type: 'AlphaNumeric', required: true, description: 'URL to receive the SabPaisa response.' },
  { name: 'amountType', type: 'Alphabet', required: false, description: 'Currency type (INR, USD).' },
  ...Array.from({ length: 20 }, (_, index) => ({
    name: `udf${index + 1}`,
    type: 'AlphaNumeric',
    required: false,
    description: `User-defined field ${index + 1}.`
  })),
  { name: 'channelId', type: 'Alphabet', required: true, description: "Channel identifier — 'W' for web, 'M' for mobile, 'npm' for npm channel." },
  { name: 'programId', type: 'AlphaNumeric', required: false, description: 'Master client code when applicable.' },
  { name: 'mcc', type: 'Numeric', required: true, description: 'Merchant category code.' },
  { name: 'transDate', type: 'Datetime', required: true, description: 'Format "YYYY-MM-DD HH:mm:ss".' }
]

const transactionEnquiryResponseParameters: IntegrationKitDoc['responseParameters'] = [
  { name: 'payerName', type: 'Alphabet', description: 'Name of the payer.' },
  { name: 'payerEmail', type: 'AlphaNumeric', description: 'Email address of the payer.' },
  { name: 'payerMobile', type: 'Numeric', description: 'Mobile number of the payer.' },
  { name: 'clientTxnId', type: 'AlphaNumeric', description: 'Transaction ID generated by the client.' },
  { name: 'payerAddress', type: 'AlphaNumeric', description: 'Address of the payer.' },
  { name: 'amount', type: 'Numeric', description: 'Transaction amount.' },
  { name: 'clientCode', type: 'Alphabet', description: 'Client code issued by SabPaisa.' },
  { name: 'paidAmount', type: 'Numeric', description: 'Total amount paid.' },
  { name: 'paymentMode', type: 'Alphabet', description: 'Payment mode used by the payer.' },
  { name: 'bankName', type: 'Alphabet', description: 'Bank name involved in the transaction.' },
  { name: 'amountType', type: 'Alphabet', description: 'Currency type such as INR or USD.' },
  ...Array.from({ length: 20 }, (_, index) => ({
    name: `udf${index + 1}`,
    type: 'AlphaNumeric',
    description: `User-defined field ${index + 1}.`
  })),
  { name: 'responseCode', type: 'Numeric', description: 'Gatewary response code (alias of statusCode).' },
  { name: 'status', type: 'Alphabet', description: 'Transaction status text such as SUCCESS, FAILED, ABORTED.' },
  { name: 'statusCode', type: 'Numeric', description: 'Transaction status code.' },
  { name: 'challanNumber', type: 'AlphaNumeric', description: 'Challan number when applicable.' },
  { name: 'sabpaisaTxnId', type: 'Alphabet', description: 'SabPaisa generated transaction ID.' },
  { name: 'sabpaisaMessage', type: 'AlphaNumeric', description: 'SabPaisa descriptive message.' },
  { name: 'bankMessage', type: 'AlphaNumeric', description: 'Message returned by the bank.' },
  { name: 'bankErrorCode', type: 'AlphaNumeric', description: 'Error code returned by the bank.' },
  { name: 'sabpaisaErrorCode', type: 'AlphaNumeric', description: 'Error code returned by SabPaisa.' },
  { name: 'bankTxnId', type: 'AlphaNumeric', description: 'Bank-provided transaction ID.' },
  { name: 'programId', type: 'AlphaNumeric', description: 'Master client code.' },
  { name: 'mcc', type: 'Numeric', description: 'Merchant category code.' },
  { name: 'transDate', type: 'Datetime', description: 'Transaction date and time returned by SabPaisa.' },
  { name: 'refundStatusCode', type: 'Numeric', description: 'Refund processing status code when applicable.' },
  { name: 'chargeBackStatus', type: 'Alphabet', description: 'Chargeback status.' },
  { name: 'settlementStatus', type: 'Alphabet', description: 'Settlement status.' },
  { name: 'rrn', type: 'AlphaNumeric', description: 'Retrieval reference number where available.' }
]

const transactionEnquirySampleEncryptedRequest = `{
  "clientCode": "DJ020",
  "statusTransEncData": "FAF63DFFCDA17834549C9D90ED546CE73D27241BA88BC1D29C57B40BF1C213A77B5F97EC93E6D1F4AEA8D0C39118B80F0547716B829C2929D08D54071EEFEC7DCCD6AEFD5E28922E39A65BAF3C722710892D3263DC03690F29EDBA90E33752EB0794ED7BEBA30C47175F58F4B26A8242F291FE278A6E3234081B30CA71AA11"
}`

const transactionEnquirySampleDecryptedRequest =
  'clientCode=DJ020&clientTxnId=TESTING090725110510177'

const transactionEnquirySampleEncryptedResponse = `{
  "clientCode": "DJ020",
  "statusResponseData": "590ECBC8D9F015D166B5699C6491FE7A1BC1AA2AE0FED1B9FEFED090A6712F5CDC77E095BB5002AFA612117E1FC930554B9FF9B9DB7786141BED1FE2AA0F8F0DD49FDB62EF99A12E635548A632A420EF6D43E2B499712584A188C519FEE9079E6A50950D53D3ED1454DAE23FBCA61CF48E21DA6C4250CA36F81101DF83BC1CD4CD7F19391820E6FC6C19E2813601310ED8B5085FE5984B0BA41B3E40EC90D98F588C431EE2E5A17C0B4B411EE979005E8BDF6014A48AC953391CBC9AB18D09225F8C108B1F4132DB431DD79099534DF8E824607A00EECB28311431875F774ECE5C0836C45CB25C7D232D48548D7739C8DCCAB380FED9BA94FA42C19BED987E5F9923F7129DBB5DF48401E8DF45950CD601C6FB559E2BE9D83238E6E2E5A34640548F78EAA3A0E4AFB2728B387EFC9EC8A09E091C781B579F17693AA8FB7929F815B690F6F9D355B1751CE09255027FBFD13E1B69EC91E6ECD1F3772FA0E209762F5C2CA56561EAF7D7CCF7BB6C5FEDC958149E05B377DFAD677C1541C65F9E1CDC215925A5E9DF03DFD35C324D3B6EE60DF49C1F2B603705F71FBE04BB60E1F9B7A62A0B1EFA5C410B044B3CC2B21C1A15750A29666AA433379B8892AD1597A99A50815E02BC666B95ED7076B721CBA2CE67E91C698A2A83875F2A27D9BD5110AE8AA2DD9EAB96E8036792A5A16E4251CC66732BF50F50CC45522310BD050D5D92D7FE7ECF627BC57E5D6DFF45C588EEAB782D4238A59D3C3DD037E66F4199E1988E6ED81A5B47CDE1564E4C392596920D872B4F006BF14E18C0DE574C767B4DBE4377F8D88FEFADCAC7B533A8CCF60B74A258D85791A7A3161C7D0731C0E209301972F74013B75268022405E15FFCA70528BA928D983DDC8E68A954C9E78E08813CE240FC4C54E9494E79EFECA24A8BD9335A99695928389BFCEABAE507569B5DF3F826AFF8120B1DD74EF2B5F6CF0332B5AE9D76B82140FA73EECF5DE84D1E5A34F71443190829A2A4E140038E1ED479B392966A10096E3737D532F5128007B8BD6029EC6C547308AEA5AC8A41D48F199CC45893A90C87917DBBCCCDCD7CE9470A0691E7DEE8301A18EE58C0A0D3E3DE0334D0F540F4B5E01D8A3259DB63D1888A4103CC814BE921F86BA9A43E65C26D373837579C208B62417449972132DF789558E1314E6353BD01745148031578"
}`

const transactionEnquirySampleDecryptedResponse =
  'payerName=VimalVishwakarma&payerEmail=NA&payerMobile=null&clientTxnId=TESTING090725110510177&payerAddress=NA&amount=null&clientCode=DJ020&paidAmount=null&paymentMode=null&bankName=null&amountType=INR&status=ABORTED&statusCode=0200&challanNumber=null&sabpaisaTxnId=null&sabpaisaMessage=Payer cancelled the transaction by itself and did not complete the&bankMessage=null&bankErrorCode=null&sabpaisaErrorCode=CH0005&bankTxnId=null&programId=DJ020&mcc=null&transDate=2025-07-09 11:05:23.0&refundStatusCode=null&chargeBackStatus=null&settlementStatus=null&rrn=null'

const refundRequestParameters: IntegrationKitDoc['requestParameters'] = [
  { name: 'clientCode', type: 'AlphaNumeric', required: true, description: 'Client code provided by SabPaisa.' },
  { name: 'amount', type: 'Numeric', required: true, description: 'Amount requested for refund.' },
  { name: 'spTxnId', type: 'Numeric', required: true, description: 'SabPaisa transaction ID to refund.' },
  { name: 'clientTxnId', type: 'AlphaNumeric', required: true, description: 'Merchant transaction ID to refund.' },
  { name: 'message', type: 'Alpha', required: true, description: 'Reason for initiating the refund.' }
]

const refundResponseParameters: IntegrationKitDoc['responseParameters'] = [
  { name: 'clientCode', type: 'string', description: 'Client code echoed back.' },
  { name: 'refundId', type: 'string', description: 'Unique refund reference generated by SabPaisa.' },
  { name: 'amount', type: 'string', description: 'Refund amount accepted by the gateway.' },
  { name: 'spTxnId', type: 'string', description: 'SabPaisa transaction ID under refund.' },
  { name: 'clientTxnId', type: 'string', description: 'Merchant transaction ID under refund.' },
  { name: 'message', type: 'string', description: 'Gateway message describing the refund outcome.' },
  { name: 'clientId', type: 'string', description: 'Unique client identifier registered with SabPaisa.' },
  { name: 'refundInitDate', type: 'string', description: 'Timestamp when the refund was initiated.' },
  { name: 'statusCode', type: 'string', description: 'Refund status code.' },
  { name: 'status', type: 'string', description: 'Human readable status of the refund.' }
]

const refundSampleEncryptedRequest = `{
  "clientCode": "SPPT1",
  "refundQuery": "CA8DDB1318137F8427836951F43B905924611681BFE15D7C37D96D55FA0374C9F6FC44ABE4808D0C64C6E34877195CAF27522502519E77CD3430634ACD14A2E105D193CEC2DF1E556AD9257D4540152371955F562D5773B5DAAC36A639432DFB0F8DC3FB0CFCDDF5C90F8B1ECB17F99165FE4A6EB9CF510436F4318A5C00BAE89E3082EEC782E20B73AC4E738C968A53F9362BAA53B7D03CBC627230AE354A073A7E88B62C6C5DE07379B8485A1BC3D7863763FF66B5CDF9848C8BF994E2C9F108376E85E3DC38"
}`

const refundSampleDecryptedRequest =
  'clientCode=SPPT1&amount=1.0&spTxnId=171600409251130529&clientTxnId=TESTING040925115251953&message=I Want my money to refund'

const refundSampleEncryptedResponse = `{
  "apiStatusCode": "01",
  "refundResponse": "C118D87F3441601936334359AE20DAC034A5FE8F534F04EC8E8A648D329E134ECA8A547C98AC727D25468363125D24BD7B0CC14F4B276D213AAE43C8B11969E318CC05FC1554E8BFF1722E2D1BB1D6ACF77E119D8D8266754532521B8AEF76714E3DC25D6E1DF8789BDC694AEF99171064AE2455B2D74ACAAEF8B30627194E03BE7156F9062A0ADA3D5DEFFFF5B5437D93B09062C667121ED1D7DAFAD90A0D2FF6C82A63439F6D2AEFA32C548222471099179314799E52E79F0172D13878EDD77EBF447607733C560E633916BC8AE5F2ACBB57325EE60A1E68C6D00443115806548DC037E1367CD025F909C68ACC4B0B8F33CDAC3AE7EEEF3DE08C86EB7E4F355573563684F027878FD5E38FD4717A2C061B0B78224100CF21B8B251421F442F052EC5B2F816ED687C58EEBE726D3BE1C2E0D74938730FCBCDE26DA9F77094BEC1D7B90172AE36507E4B07",
  "apiStatusDescription": "API Request accepted."
}`

const refundSampleDecryptedResponse = `{
  "spTxnId": "171600409251130529",
  "clientTxnId": "TESTING040925115251953",
  "refundInitDate": "2025-09-04 06:28:08",
  "amount": "1.0",
  "clientCode": "SPPT1",
  "clientId": "19142",
  "message": "Refund was already submitted.",
  "statusCode": "0600",
  "status": "REFUND_INITIATED"
}`

export const apiReferenceKits: IntegrationKitDoc[] = [
  {
    id: 'transaction-enquiry',
    name: 'Transaction Enquiry API',
    overview: {
      purpose:
        'Encrypt client credentials and transaction identifiers to retrieve the latest SabPaisa payment status.',
      useCases: [
        'Reconciling asynchronous transactions or ambiguous payment outcomes',
        'Scheduled reconciliation for offline collections or delayed banking responses',
        'Support workflows where customer care needs to confirm payment status quickly'
      ],
      prerequisites: [
        'Valid SabPaisa client code with transaction enquiry enabled',
        'AES and HMAC keys shared securely by SabPaisa',
        'Network access to the stage or production enquiry endpoints'
      ],
      setup: [
        'Concatenate required key-value pairs into a plain string using & separators.',
        'Encrypt the plain string with AES256HMACSHA384HEX (AES-GCM + HMAC-SHA384).',
        'POST the JSON body containing clientCode and statusTransEncData to the enquiry endpoint.',
        'Decrypt statusResponseData with the same AES and HMAC keys, then parse the plain string into fields.'
      ]
    },
    sampleCodeLink: 'https://stage-txnenquiry.sabpaisa.in/SPTxtnEnquiry/getTxnStatusByClientxnId',
    endpoints: {
      sandbox: 'https://stage-txnenquiry.sabpaisa.in/SPTxtnEnquiry/getTxnStatusByClientxnId',
      production: 'https://txnenquiry.sabpaisa.in/SPTxtnEnquiry/getTxnStatusByClientxnId'
    },
    requestFormat: {
      transport: 'Send a POST request with a JSON body containing clientCode and statusTransEncData.',
      headers: ['Accept: application/json', 'Content-Type: application/json'],
      bodyNotes: [
        'statusTransEncData must be generated from the plain string using the AES256HMACSHA384HEX algorithm.',
        'Ensure the clientTxnId matches the identifier used during transaction initiation.',
        'Throttle automated schedulers to avoid concurrent enquiries for the same transaction.'
      ]
    },
    requestParameters: transactionEnquiryRequestParameters,
    sampleEncryptedRequest: transactionEnquirySampleEncryptedRequest,
    sampleDecryptedRequest: transactionEnquirySampleDecryptedRequest,
    responseFormat: {
      transport: 'SabPaisa returns JSON containing statusResponseData which must be decrypted to read fields.',
      notes: [
        'Validate the decrypted payload and persist it before updating downstream systems.',
        'Status codes: 0000=Success, 0100=Initiated, 0200=Aborted, 0300=Failed, 0400=Challan generated, 0999=Unknown, 404=Transaction not found.',
        'Log the encrypted response string to assist SabPaisa support if decryption fails.'
      ]
    },
    responseParameters: transactionEnquiryResponseParameters,
    sampleEncryptedResponse: transactionEnquirySampleEncryptedResponse,
    sampleDecryptedResponse: transactionEnquirySampleDecryptedResponse
  },
  {
    id: 'refund',
    name: 'Refund API',
    overview: {
      purpose:
        'Initiate a refund by encrypting the refundQuery payload and submitting it to SabPaisa gateway.',
      useCases: [
        'Processing customer-initiated refund requests after successful payments',
        'Handling partial or full refunds triggered by operations staff',
        'Automating refunds as part of reconciliation or cancellation workflows'
      ],
      prerequisites: [
        'SabPaisa refund API access with AES/HMAC keys provisioned',
        'Original SabPaisa transaction successfully completed',
        'Merchant back office process to log refund identifiers for audit'
      ],
      setup: [
        'Create the plain string containing clientCode, amount, spTxnId, clientTxnId, and message.',
        'Encrypt the string via AES256HMACSHA384HEX, placing the cipher text in refundQuery.',
        'POST clientCode and refundQuery to the refund endpoint.',
        'Decrypt refundResponse to read refundId, status, and other metadata.'
      ]
    },
    sampleCodeLink: 'https://stage-gateway.sabpaisa.in/sabpaisa/refund',
    endpoints: {
      sandbox: 'https://stage-gateway.sabpaisa.in/sabpaisa/refund',
      production: 'https://gateway.sabpaisa.in/sabpaisa/refund'
    },
    requestFormat: {
      transport: 'Send a POST request with a JSON body containing clientCode and refundQuery.',
      headers: ['Accept: application/json', 'Content-Type: application/json'],
      bodyNotes: [
        'Message should clearly describe the refund reason for audit.',
        'Use the exact spTxnId and clientTxnId from the original transaction.',
        'Regenerate the encrypted payload for every refund attempt; do not reuse previous cipher text.'
      ]
    },
    requestParameters: refundRequestParameters,
    sampleEncryptedRequest: refundSampleEncryptedRequest,
    sampleDecryptedRequest: refundSampleDecryptedRequest,
    responseFormat: {
      transport: 'SabPaisa responds with apiStatusCode and refundResponse. Decrypt refundResponse for details.',
      notes: [
        'Persist refundId and status for downstream reconciliation.',
        'Monitor statusCode for transitions such as REFUND_INITIATED or REFUNDED.',
        'API status codes: 00=Request processed successfully, 01=Request accepted, 02=Unable to decrypt, 03=Bad request, 04=Invalid client code, 05=Support system, 06=Invalid amount, 07=Invalid clientTxnId, 08=Invalid SabPaisa txnId, 09=Refund rejected, 10=Refunded, 11=Refund initiated, 12=Failed.',
        'Refund status codes: 0100=INITIATED, 0200=ABORTED, 0300=FAILED, 0400=CHALLAN_GENERATED, 0500=CHALLAN_ENQUIRED, 0600=REFUND_INITIATED, 0700=REFUNDED, 0800=SETTLED.',
        'Escalate with SabPaisa support if apiStatusCode indicates decryption or validation issues.'
      ]
    },
    responseParameters: refundResponseParameters,
    sampleEncryptedResponse: refundSampleEncryptedResponse,
    sampleDecryptedResponse: refundSampleDecryptedResponse
  }
]
